# Generated by Django 3.1.3 on 2020-11-18 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_medstore'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='员工用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('name', models.CharField(max_length=32, verbose_name='员工姓名')),
                ('phonenumber', models.ImageField(max_length=11, upload_to='', verbose_name='联系方式')),
                ('desc', models.CharField(max_length=256, verbose_name='员工简介')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.medstore', verbose_name='药店')),
            ],
        ),
    ]
