# Generated by Django 3.1.3 on 2020-11-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20201119_2126'),
    ]

    operations = [
    ]
