# Generated by Django 3.1.3 on 2020-11-18 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_staff'),
        ('store', '0002_medstore'),
        ('medicine', '0004_cart_medicine'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='订单ID')),
                ('addr', models.CharField(blank=True, max_length=128, null=True, verbose_name='收货地址')),
                ('pay_method', models.SmallIntegerField(choices=[(0, '现金支付'), (1, '微信支付'), (2, '支付宝')], default=0, verbose_name='支付方式')),
                ('total_count', models.IntegerField(default=1, verbose_name='数量')),
                ('med_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='药品总价')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('transit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='配送费')),
                ('order_status', models.SmallIntegerField(choices=[(0, '待支付'), (1, '待配送'), (2, '已送达'), (3, '待评价'), (4, '已完成')], default=1, verbose_name='订单状态')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('drugstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.medstore', verbose_name='药店')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='操作员')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='数目')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('comment', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='评论')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders', verbose_name='订单')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine', verbose_name='药品')),
            ],
        ),
    ]
