# Generated by Django 3.1.3 on 2020-11-18 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordergoods_orders'),
    ]

    operations = [
    ]
