# Generated by Django 3.1.3 on 2020-11-19 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('orders', '0004_auto_20201119_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='顾客'),
        ),
        migrations.AddField(
            model_name='orders',
            name='sale_method',
            field=models.SmallIntegerField(choices=[(0, '线下销售'), (1, '线上小程序销售')], default=0, verbose_name='销售方式'),
        ),
    ]
