# Generated by Django 3.1.3 on 2020-11-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201119_1943'),
    ]

    operations = [
    ]
