# Generated by Django 3.1.3 on 2020-11-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='顾客用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('name', models.CharField(max_length=32, verbose_name='微信昵称')),
                ('phonenumber', models.ImageField(max_length=11, upload_to='', verbose_name='联系方式')),
                ('desc', models.CharField(max_length=256, verbose_name='备注')),
            ],
        ),
    ]
