# Generated by Django 2.2.1 on 2020-11-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='联系方式')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户TOKEN')),
                ('addr', models.CharField(blank=True, max_length=32, null=True, verbose_name='收货地址')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='顾客姓名')),
                ('desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
            ],
        ),
    ]
