# Generated by Django 2.2.1 on 2020-11-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinecode', models.CharField(max_length=14, verbose_name='国家药品编码')),
                ('name', models.CharField(max_length=20, verbose_name='药品名称')),
                ('type', models.CharField(max_length=20, verbose_name='药品种类')),
                ('desc', models.CharField(max_length=256, verbose_name='药品简介')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='药品价格')),
                ('unite', models.CharField(max_length=20, verbose_name='药品生产单位')),
                ('image', models.ImageField(upload_to='medicine_image', verbose_name='药品图片')),
                ('stock', models.IntegerField(default=1, verbose_name='药品库存')),
                ('sales', models.IntegerField(default=0, verbose_name='药品销量')),
                ('status', models.SmallIntegerField(choices=[(0, '暂无'), (1, '暂停销售')], default=1, verbose_name='药品状态')),
                ('drugstore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.medstore', verbose_name='药店')),
            ],
            options={
                'verbose_name': '药品SKU',
                'verbose_name_plural': '药品SKU',
                'db_table': 'medicine_SKU',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_goods_num', models.IntegerField(default=1)),
                ('C_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.Medicine')),
                ('C_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.medstore')),
            ],
        ),
    ]
