# Generated by Django 3.1.3 on 2020-11-18 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20201118_1028'),
    ]

    operations = [
    ]
