# Generated by Django 3.1.3 on 2020-11-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_auto_20201118_1029'),
    ]

    operations = [
    ]
